### ISSUE TITLE
Is it possible  to make ZipFile seekable?

### ISSUE THREAD

**Issue by Leojangh** [zip-rs/zip-old#424] opened 2024-01-02 04:45 UTC
The [zip::read::ZipFile](https://docs.rs/zip/0.6.6/zip/read/struct.ZipFile.html).
My geuss is impossible.

**Comment by RandomInsano** [comment] 2024-01-14 02:46
I'm just passing by, but searching for existing issues that contain "Seek" provided this:
https://github.com/zip-rs/zip/issues/223

**Comment by Pr0methean** [comment] 2024-05-06 02:51
Duplicate of #223.

**Closed by Pr0methean** 2024-05-06 02:51 UTC
